services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - /container_data/uptime-kuma/data:/app/data
    networks:
      - proxy_network
    environment:
      - VIRTUAL_HOST=status.skyserver.fr
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=status.skyserver.fr
      - LETSENCRYPT_EMAIL=teomullerheddar@gmail.com

networks:
  proxy_network:
    external: true